<?php

/**
 * BlogPostVoteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BlogPostVoteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BlogPostVoteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BlogPostVote');
    }
}