BlogPost:
  options:
    collate: utf8_unicode_ci
    charset: utf8
  actAs:
    Timestampable:   ~
  columns:
    id:               { type: integer(4), notnull: true, primary: true, autoincrement: true, unsigned: true }
    author_id:
      type: integer
    title:            { type: string(100), notnull: true }
    source:           { type: text, notnull: true }
    rating:           { type: integer, default: 0, notnull: true }
  relations:
      Author:
        class: sfGuardUser
        local: author_id
        foreign: id
        foreignAlias: posts

BlogPostVote:
  options:
    collate: utf8_unicode_ci
    charset: utf8
  columns:
    id:               { type: integer(4), notnull: true, primary: true, autoincrement: true, unsigned: true }
    post_id:          { type: integer(4), notnull: true, unsigned: true }
    author_id:        { type: integer, notnull: true }
  relations:
    Post:
      local:          post_id
      foreign:        id
      class:          BlogPost
      foreignAlias:   votes
      onDelete:       CASCADE

